services:
  api:
    build:
      context: backend/.
      dockerfile: Dockerfile
    volumes:
      - ./backend/media:/vol/web/media
      - backend-static:/vol/web/static
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: gunicorn cinema_service.wsgi:application -b 0.0.0.0:8000 --workers 4 --threads 10

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend-static:/app/dist
      - backend-static:/app/static
      - ./backend/media:/app/media
    env_file:
      - .env
    depends_on:
      - api
      - frontend-builder
    restart: always

  frontend-builder:
    build:
      context: frontend/.
      dockerfile: Dockerfile
    volumes:
      - frontend-static:/app/dist
    env_file:
      - .env
    command: npm run build

volumes:
  backend-static:
  frontend-static:
